#Minecraft server properties
#Mon Aug 10 17:38:12 KST 2026
accepts-transfers=true
allow-flight=false
allow-nether=true
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
bug-report-link=
debug=false
difficulty=peaceful
enable-command-block=true
enable-jmx-monitoring=false
enable-query=false
enable-rcon=false
enable-status=true
enforce-secure-profile=false
enforce-whitelist=false
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=adventure
generate-structures=true
generator-settings={"biome"\:"minecraft\:the_void","features"\:false,"lakes"\:false,"layers"\:[{"block"\:"minecraft\:air","height"\:1}],"structure_overrides"\:[]}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla
level-name=world
level-seed=
level-type=minecraft\:flat
log-ips=true
max-chained-neighbor-updates=1000000
max-players=100
max-tick-time=60000
max-world-size=29999984
motd=Paper 1.21.8 Server
network-compression-threshold=256
online-mode=true
op-permission-level=4
pause-when-empty-seconds=-1
player-idle-timeout=0
prevent-proxy-connections=false
pvp=true
query.port=25565
rate-limit=0
rcon.password=
rcon.port=25575
region-file-compression=deflate
require-resource-pack=true
resource-pack=https\://mounted-close-heart-whose.trycloudflare.com/RPGMaker-Pack-20260809-122924.zip
resource-pack-id=36287fa8-95d7-430b-b0d9-d531d913b9ba
resource-pack-prompt={"text"\:"RPGMaker 리소스팩을 다운로드합니다.","color"\:"gold"}
resource-pack-sha1=6c4090f3ba08026c56259faf0b5cd479dc0f66c0
server-ip=
server-port=25565
simulation-distance=10
spawn-monsters=false
spawn-protection=0
sync-chunk-writes=true
text-filtering-config=
text-filtering-version=0
use-native-transport=true
view-distance=10
white-list=false
